---
- name: squid-allowed-sites
  hosts: '{{ target }}'
  vars:
  become: True
  become_user: root
  tasks:
    - name: allowed site
      lineinfile:
        path: /etc/squid/allowed_sites
        state: present
        owner: root
        group: squid
        mode: 440
        backup: yes
        line: "{{ allowed_site }}"
      register: squid_allowed

    - name: squid service reload on conf change
      systemd:
        name: squid
        state: reloaded
      when: squid_allowed.changed
